server:
  port: 9527
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: gateway9527
    prefer-ip-address: true
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启动态路由
      routes:
        - id: payment_routh
          uri: lb://cloud-payment-service     # 1、lb启动负载均衡     1、利用微服务名为地址进行路由
          predicates:
            - Path=/payment/get/**

        - id: payment_routh1
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/test1/**

        - id: payment_routh2

          uri: lb://cloud-payment-service     # 1、lb启动负载均衡     1、利用微服务名为地址进行路由
          predicates:
            - Path=/payment/create


